spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/anomalies
    username: dev
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
  flyway:
    enabled: false