spring:
  config:
    import: classpath:secrets.yml
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/${secrets.db-name}
    username: ${secrets.db-user}
    password: ${secrets.db-password}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect