name: Kotlin format check (spotless, ktfmt)

on: [ push, pull_request ]

jobs:
  kotlin_format_check:
    name: "Kotlin Format Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - run: |
          cd rest
          mvn spotless:check